eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
 
management:
  endpoint:
    health:
      show-details: always
      
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9098
spring:
  application:
    name: coupon-service
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
      
  zipkin:
    base-url: http://localhost:9411
      

